### ISSUE TITLE
Positioning in gui throws an error

### ISSUE THREAD

**Issue by albertoferna** [RubendeBruin/DAVE#33]
Hello,

first of all, congratulations on this piece of software, it is shaping up quite nicely.
I was just playing around with the recent version and I found a weird bug. I'll explain why I think it is weird in a moment, but first to the issue.
I installed DAVE in a windows machine with a conda installation. Conda version is 4.9.1. Since I had DAVE in the past, I renamed the old environment to DAVE_old. The new version installed, 1.5.4, is done with the same installation procedure, that is:
`conda create -n DAVE DAVE -c conda-forge
activate DAVE`
So, nothing new here. When I launch the GUI with python -m DAVE.run_gui everything looks good. However, when I add a point, a rigid body, etc I get an error. For example, for a point "'Arrow' object has no attribute 'setTransform'"
Looking at the code, it seems to me that it is trying to position the actor representing the object on the scene.
The same error is thrown if I try to change the position of the object using the GUI or the console. Of course, the actor in the scene does not move.
It may not be relevant to anything beyond presentation but it would make hard any sort of debugging.
The weird part comes from the old version. If I use DAVE_old, my old environment, it still works. The version there is 1.4.0, so I went ahead and forced that version on the new environment instead of 1.5.4. However, the error still appears.
All this makes me think of some sort of incompatibility with one of the required packages. I cannot do it now, but I'll try to dump a list of packages in both environments to see what are the differences

regards

**Comment by albertoferna** [comment]
I have some more news. If I force an update of just DAVE in the old installation, all works well. Thus, the likely culprit is another package.
I'm attaching two files here. New_DAVE is an comletely new install of DAVE in a new environment, and it is the one giving problems. Old_DAVE is the previous install of dave updated to 1.5.4, and it works correctly.
[New_DAVE_specs.txt](https://github.com/RubendeBruin/DAVE/files/5529588/New_DAVE_specs.txt)
[Old_DAVE_specs.txt](https://github.com/RubendeBruin/DAVE/files/5529589/Old_DAVE_specs.txt)
When I have a few minutes I'll try to compare them to see if I can find the problematic package

**Comment by albertoferna** [comment]
I've located the problematic package. Turning back vedo to version 2020.3.4 fixes the issue. I don't know what changes vedo did from 2020.3.4 to 2020.4.1, but the recent one throws the error

**Comment by RubendeBruin** [comment]
Hi @albertoferna , thanks for your extensive report! I will see if I can reproduce the error here and see if I have to adapt DAVE or fix something in vedo.

**Comment by RubendeBruin** [comment]
You are completely correct. setTransform has been replaced with applyTransform in vedo 2020.4.1

In DAVE I will refactor this to use the underlying vtk methods (SetUserMatrix and SetUserTransform) directly. For now the easiest solution is indeed to downgrade vedo to 2020.3.4

**Comment by albertoferna** [comment]
Glad to be of help. I guess I should leave this issue open right?

**Comment by RubendeBruin** [comment]
Yes, please keep it open for now.
The fix in in branch SPMT at the moment and will be part of the next release.

**Comment by RubendeBruin** [comment]
Fixed!
