### ISSUE TITLE
No pyo3d available for python 3.9

### ISSUE THREAD

**Issue by RubendeBruin** [RubendeBruin/DAVE#35]
The trick is to first create an environment with python 3.8, then install DAVE in that environment.

This can be done as follows:

conda env create -n DAVE python=3.8

activate DAVE

conda install -c conda-forge DAVE

**Comment by Ross1993Hall** [comment]
Hi Reuben ,

I keep getting the 'No module named 'pyo3d'' error . I've tried the above suggestion and it doesn't seem to work . 
do you have any additional suggestions ?

Ross

**Comment by RubendeBruin** [comment]
Fixed with version 1.5.6
