### ISSUE TITLE
Shackle degrees of freedom not saved

### ISSUE THREAD

**Issue by michielbicker** [RubendeBruin/DAVE#63]
Ha @RubendeBruin,

I found another issue related to shackles. The degrees of freedom are not saved, i.e. if I have a shackle that is free to move in all directions and I save and re-open the model all degrees of freedom of the shackle are fixed again. Could you have a look at that?

**Comment by RubendeBruin** [comment]
Confirmed and fixed in next release

**Comment by RubendeBruin** [comment]
Fix implemented in version 1.7.1
