### ISSUE TITLE
Solved position for shackles in connection not saved

### ISSUE THREAD

**Issue by michielbicker** [RubendeBruin/DAVE#64]
Ha @RubendeBruin,

I noticed that the solved position of a shackle that is 'managed' by a connection is not saved (a shackle in a pad-eye). Would it be possible to save this such that the complete solution is saved? Now if I re-open a model, I have difficulties solving it again, since these shackles are in a strange position.

![image](https://user-images.githubusercontent.com/89965911/133404929-39e25efb-5408-4fd7-a796-e911d60773ff.png)

Thanks!

**Comment by RubendeBruin** [comment]
Hi @michielbicker , this is (was) a bug in saving the state of a geometric-contact. I think I have solved it.
Should be correct now in the master branch and on pypi (version 1.7.12). Conda will follow in a few hours.
