### ISSUE TITLE
show trows an error in jupyter lab

### ISSUE THREAD

**Issue by albertoferna** [RubendeBruin/DAVE#88]
Hello,
It's been a while since I tried anything in DAVE. I installed the current version today and it looks like a lot has been going on. Congratulations on the great work!
I'm trying to see what can be done from a notebook to check the potential for automation. I was just trying a very simple example but I could not get visual feedback from it.
All I'm doing is:
```
from DAVE import *
from DAVE.jupyter import *
s = Scene()
s.new_frame('Demo')
show(s)
```
I get back 'NoneType' object has no attribute 'GetInitialized'
I'm running this in jupyter lab, but I also tried in jupyter notebook and ipython. This is a windows 10 machine. DAVE install was done with conda and I added nodejs, k3d, ipyvtk-simple at different stages, none of them solved the issue.
I tried to run some of the example notebooks in the documentation, but the visual part always failed. Also, it seems that view(scene) is still in the documentation, but it does not get imported (not being picky here, just letting you know). For example it is mentioned in https://github.com/RubendeBruin/DAVE-book/blob/master/reporting.md
I wonder if the problem is with my setup or if there has been some change that broke visualization in jupyter.

**Comment by RubendeBruin** [comment]
Hi @albertoferna , sorry I completely missed your post. Your code should work, let me look into it

**Comment by RubendeBruin** [comment]
Thanks for reporting this

The error originates from a change in vedo (the package doing the visuals) and should be fixed in the next version of vedo.
I've also implemented a work-around in DAVE which should prevent this from occurring.

DAVE release 1.8.1 (available soon) solves this issue
