### ISSUE TITLE
Calculate GZ Curve for STL Geometry

### ISSUE THREAD

**Issue by asadabbas09** [RubendeBruin/DAVE#98]
Thanks for making this amazing tool freely available.

I was wondering if is there a notebook or tutorial which would guide me through how to calculate the GZ curve, given an input 3D STL geometry.

All I want to do is to load an STL file and calculate GZ Curve on Linux.

Do I need the equilibrium core module for this purpose?

**Comment by RubendeBruin** [comment]
Hi @asadabbas09 , thanks for reaching out. Calculating the GZ curve involves calculating the equilibrium position and resulting CoB for a range of heel angles. This is something that the equilibrium core takes care off.

I should be able to compile the core on linux, done it in the past, and provide it to you. What linux distribution are you running?

**Comment by RubendeBruin** [comment]
Oh, and which python version. (3.8, 3.9)

**Comment by asadabbas09** [comment]
thanks @RubendeBruin  I'm using python 3.9

Also, is there any tutorial about loading STL files (in python) and calculating the GZ curve? I can see there are some notebooks, but they seem to work with scenes etc. and not with STL files.

**Comment by RubendeBruin** [comment]
Hi @asadabbas09 , a `Scene` is always required. It is the "world" that nodes live in.

To calculate the GZ curve you would need at least two nodes:
1. a Rigidbody-node to model the movement and the center of gravity "G"
2. a buoyancy-shape node attached to the rigid-body is then used to model the displaced volume.

The .stl file is then loaded by the buoyancy-shape node.

<img width="856" alt="image" src="https://user-images.githubusercontent.com/34062862/201345169-afeb653d-8013-44e1-aa52-880576ae5a3d.png">


```
s = Scene()

# code for Body
s.new_rigidbody(name='Body',
                mass=5,
                cog=(0, 0,  0),
                fixed=False )

# code for Buoyancy mesh
mesh = s.new_buoyancy(name='Buoyancy mesh',
          parent='Body')
mesh.trimesh.load_file(r'res: cube.obj', scale = (5.0,2.0,1.0), rotation = (0.0,0.0,0.0), offset = (0.0,0.0,0.0))
```

In your case replace `res: cube.obj` with the path of you .stl file.

Finally the GZ curve is then calculated using:

```
from DAVE.marine import GZcurve_DisplacementDriven

displacement_kN = mesh.displacement * s.rho_water * s.g

stab = GZcurve_DisplacementDriven(scene = s,
                    vessel_node = "Body",
                    displacement_kN=displacement_kN,
                    minimum_heel= 0,
                    maximum_heel=40,
                    steps=40,
                    allow_surge=False,
                    allow_sway=False,
                    allow_yaw=False,
                    allow_trim=False)
```

stab is a dict with 'heel' and 'GZ'.

What are you going to use DAVE for? Do you already have the .stl files for the shapes?

**Comment by RubendeBruin** [comment]
This is the equilibrium executable for x64 linux, python 3.9 can be downloaded from here: https://open-ocean.org/files/pyo3d.cpython-39-x86_64-linux-gnu.so

please let me know if this works on your machine.

**Comment by asadabbas09** [comment]
thanks, @RubendeBruin , it worked flawlessly. But now it's saying 

```
THIS MODULE HAS EXPIRED 
Contact the author for a new copy of the compiled EquilibriamCore
```
Can you update the core file for x64 linux, python 3.9 ?

**Comment by asadabbas09** [comment]
thanks @RubendeBruin I'm using updated `.so` file. I can see that equilibrium core version has changed from `2.48` to `2.49` but  still getting same error message

```
Equilibrium-core version = 2.49 from /home/asad/Documents/Optimisation/DAVE1/pyo3d.cpython-39-x86_64-linux-gnu.so
default resource folders:
/home/asad/miniconda3/envs/dave/lib/python3.9/site-packages/DAVE/resources
/home/asad/DAVE_models
/home/asad/Documents/Optimisation/DAVE1

 ~~~ Equilibrium core (for DAVE) ~~~ 
 Evaluation version - valid 2022 
 Version = EXPERIMENTAL evaluation version


 THIS MODULE HAS EXPIRED. 
 Contact the author for a new copy of the compiled EquilibriumCore (pyo3d) library. See https://www.open-ocean.org/equilibrium-core/ for details.%     
```

**Comment by RubendeBruin** [comment]
you are correct.
Updated the file again, should now active till April 1
